### ISSUE TITLE
nongrav_info has no key 'radius'

### ISSUE THREAD

**Issue by Pachacoti** [rahil-makadia/grss#65]
After upgrading `grss` to 4.0.2, I started to have the following error with defining `body_radius = nongrav_info['radius']`:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'radius'
```
The keys in `nongra_info` all seem to be related a{1,2,3} and nongrav coefficients for the nongrav force model, nothing called `'radius'` there. To circumvent this error and proceed, I instead have to use `body_radius = 0.` if this parameter is unknown. I wonder if this is a bug?

**Comment by rahil-makadia** [comment]
For now I would keep your temporary fix. This is a consequence of the docs getting updated from the `dev` branch. The change that lets you directly use nongrav_info['radius'] is already sitting on the `dev` branch but I am waiting on a couple other things on the `gaia` branch before I can merge everything. This may take a while, but it's on its way. In the future the `FitSimulation` class will directly read in the radius from the `nongrav_info` dict so you won't have to worry about it.
