### ISSUE TITLE
kepler_solve warning

### ISSUE THREAD

**Issue by Pachacoti** [rahil-makadia/grss#73]
Occasionally I'll have the following line popping out:
```
utilities.cpp: WARNING: kepler_solve did not converge in 100 iterations!!! F: 7.91029
```
The value after `F: ` will vary from case to case though. I wonder how this may affect the best-fit results?

**Comment by rahil-makadia** [comment]
Can you send a script that reproduces this?

**Comment by Pachacoti** [comment]
It's basically the same as those in your examples, except that I run for different objects in the same session. I estimate the likelihood of the occurrence is something like once in 50-100 samples. I can't reproduce the warning if I pick the specific object to which the warning occurs and run it in a new session.

Here's my example with 2016 QU1 after `fit_sim.filter_lsq()`:
```
Iteration		Unweighted RMS		Weighted RMS 		Chi-squared		Reduced Chi-squared
1			 0.589			 0.733			 113.935			 0.556
2			 0.584			 0.732			 113.597			 0.554
Converged without rejecting outliers. Starting outlier rejection now...
3			 0.428			 0.615			 80.181			 0.395
4			 0.428			 0.614			 80.047			 0.394
Converged after rejecting outliers. Rejected 1 out of 106 optical observations.
utilities.cpp: WARNING: kepler_solve did not converge in 100 iterations!!! F: -1.02067e-05
```
As I gave more tests, it seems that the final result is not affected by this warning. But I just can't understand why it occasionally shows up.

**Comment by rahil-makadia** [comment]
As I've mentioned in previous issues, I wouldn't recommend running more than one object in one session. There is a chance that the buffer from the C++ code wasn't flushed before the next python loop iteration started running (so the warning you're seeing might be from a previous object in the session). 

Please re-open this issue if you find individual cases that trigger this warning. It simply says that the Kepler equation solver might not have converged. The specific example you gave with a function value of ~1e-5 is probably good enough and I just have too tight of a convergence criterion but if you re-find the object that had the original F value of ~8, let me know

**Comment by Pachacoti** [comment]
After checking the output log, I did manage to find a case where F~8:
```
Read in 1302 observations from the MPC.
	WARNING: At least one unknown observation mode in the data.
	WARNING: At least one deprecated star catalog in the data.
	Filtered to 1302 observations that satisfy the time range and accepted observatory constraints.
Applying Eggl et al. (2020) debiasing scheme to the observations.
	Unknown star catalog: GSC
	Unknown star catalog: UNK
	No debiasing needed for 434 observations.
	Debiased 738 observations.
	No bias information for 130 observations.
Applying Vereš et al. (2017) weighting scheme to the observations.
	Using 699 CCD utilities.cpp: WARNING: kepler_solve did not converge in 100 iterations!!! F: 7.91029
observations with station-specific weight rules.
Applying sqrt(N/4) deweighting scheme.
	Deweighted 324 observations.
Read in 152 Gaia observations from gaiafpr
```
I think you're correct that this should be from some buffer issue, as I don't think fetching observations should not involve solving Kepler's equation.

Adding `sleep(10)` for instance after each loop seems to solve the problem.

**Comment by rahil-makadia** [comment]
What object was this for?

**Comment by Pachacoti** [comment]
137052. The previous one I ran for was 136874.
